version: "3"

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - 5432:5432
    restart: unless-stopped
  # app:
  #   restart: always
  #   build: .
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - postgres-db
  #   ports:
  #     - 3000:3000
  #   command: yarn dev
